### ISSUE TITLE
Life Expectancy and GDP in 5 Nations (DVP)

### ISSUE THREAD

**Issue by asadmehdi785** [mattir/dvp-u6-who-data#1]
### Criteria 1: DataFrames and CSV
* _Score Level:_ 4
* _Comment(s):_ Data from a provided CSV file is successfully loaded into a DataFrame.
 
### Criteria 2: Implementation of visualizations
* _Score Level:_ 4
* _Comment(s):_ The Jupyter notebook includes
plots for all project data with Seaborn, using appropriate and meaningful color palettes to display insights about the data.
 
### Criteria 3: Responses and Blog post
* _Score Level:_ 4
* _Comment(s):_ The Jupyter notebook includes inline responses analyzing data for all prompts. The blog post successfully expands on those ideas and includes images of the correct Seaborn plots.

### Overall Score: 12/12
Overall, outstanding work with this project! You did a good job loading in the given data into a DataFrame and were able to use that data along with Seaborn to create some interesting visualizations. Great work that!

With regards to your blog post, I thought it was very well written and you did an excellent job overall with it. I especially liked how you published it on the web on your own personal website, that was very nice to see! There were just a couple of things I wanted to address concerning the write-up; firstly, a few of the charts in the beginning had labels that were a bit hard to read without zooming in. Secondly, to expand on the ideas you wrote about it can be helpful to incorporate outside sources into the post as well. Consider doing some more outside research on the topic and bring some extra context to your write-up!

Great work overall! I hope you enjoyed the course!

**Comment by mattir** [comment]
Thank you for your feedback.
